stages:
  - test
  - build

build-master:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" # $CI_REGISTRY
    - docker build --pull -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - master

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" # $CI_REGISTRY
    - docker build --pull -t "$IMAGE_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_REF_SLUG"
  except:
    - master

test_all:
  image: node:10.12.0-alpine
  stage: test
  variables:
    DB_URL: mongodb://mongo:27017
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  script:
   - npm install
   - sleep 10
   - npm run test
  tags:
    - docker
  cache:
    paths:
    - node_modules/